In [ ]:
# Pivot Tables

In [2]:
import pandas as pd

df = pd.read_json("students2.json")
print(df)

    name    city  subject  marks
0  Sahil   Delhi     Math     90
1  Sahil   Delhi  Science     85
2   Riya  Mumbai     Math     88
3   Riya  Mumbai  Science     92
4   Aman   Delhi     Math     78
5   Aman   Delhi  Science     80

In [ ]:
# What is a Pivot Table?
# Pivot table reorganizes data to show summary in a matrix form.

In [ ]:
# Example idea

# Rows → city
# Columns → subject
# Values → marks

In [2]:
# Basic Pivot Table

pd.pivot_table(df, values="marks", index="city", columns="subject")

subject  Math  Science
city
Delhi    84.0     82.5
Mumbai   88.0     92.0

In [ ]:
# ndex → rows
# columns → column headers
# values → data to aggregate

In [3]:
# Default Aggregation
# By default:

aggfunc = "mean"

In [4]:
# Aggregation Function:Sum
pd.pivot_table(df, values="marks", index="city", columns="subject", aggfunc="sum")

subject  Math  Science
city
Delhi     168      165
Mumbai     88       92

In [5]:
# Aggregation Function:MAX
pd.pivot_table(df, values="marks", index="city", columns="subject", aggfunc="max")

subject  Math  Science
city
Delhi      90       85
Mumbai     88       92

In [6]:
# Aggregation Function:MIN
pd.pivot_table(df, values="marks", index="city", columns="subject", aggfunc="min")

subject  Math  Science
city
Delhi      78       80
Mumbai     88       92

In [7]:
# Aggregation Function:COUNT
pd.pivot_table(df, values="marks", index="city", columns="subject", aggfunc="count")

subject  Math  Science
city
Delhi       2        2
Mumbai      1        1

In [8]:
# Multiple Aggregations
pd.pivot_table(
    df,
    values="marks",
    index="city",
    columns="subject",
    aggfunc=["mean", "max"]
)

         mean          max
subject  Math Science Math Science
city
Delhi    84.0    82.5   90      85
Mumbai   88.0    92.0   88      92

In [18]:
import pandas as pd

df = pd.read_json("students2.json")
print(df)

    name    city  subject  marks
0  Sahil   Delhi     Math    NaN
1  Sahil   Delhi  Science   85.0
2   Riya  Mumbai     Math    NaN
3   Riya  Mumbai  Science   92.0
4   Aman   Delhi     Math   78.0
5   Aman   Delhi  Science   80.0

In [21]:
# Fill Missing Values in Pivot
vc = pd.pivot_table(
    df,
    values="marks",
    index="city",
    columns="subject",
    fill_value=0
)
# Replaces NaN with 0.

In [23]:
pd.pivot_table(vc, values="marks", index="city", columns="subject")

KeyError: 'marks'

In [10]:
# Add Margins (Totals)
pd.pivot_table(
    df,
    values="marks",
    index="city",
    columns="subject",
    margins=True
)
# All → total

subject       Math    Science    All
city
Delhi    84.000000  82.500000  83.25
Mumbai   88.000000  92.000000  90.00
All      85.333333  85.666667  85.50