In [55]:
# GroupBy & Aggregation in pandas
import pandas as pd

df = pd.read_json("data1.json")
print(df)

     name    city  marks  age
0    None   Delhi     90   24
1    Riya  Mumbai     85   23
2    Aman   Delhi     88   24
3    Neha  Mumbai     92   23
4   Karan   Delhi     78   24
5  Charan   Delhi     78   24
6    None   Delhi     78   24

In [ ]:
# What is GroupBy?
# GroupBy means grouping rows based on a column and applying operations.

In [16]:
df.groupby("city")

# This does NOT show output directly.It creates a grouped object.

In [23]:
# Mean marks by city
# vc=print(df.groupby("city")["marks"].mean())
# print(vc)
(df.groupby("city")["marks"].mean()) as MeanMarks
print()
# bc=print(df.groupby("city")["age"].mean()) as MeanAge
# print(bc)
(df.groupby("city")["age"].mean()) AS MeanAge

SyntaxError: invalid syntax (2583359244.py, line 4)

In [34]:
# Mean marks by city
print(df.groupby("city")["marks"].mean().reset_index(name="MeanMarks"))
# print(vc)

print(df.groupby("city")["age"].mean().reset_index(name="MeanAge"))
# print(bc)

     city  MeanMarks
0   Delhi  85.333333
1  Mumbai  88.500000
     city  MeanAge
0   Delhi     24.0
1  Mumbai     23.0

In [6]:
# Mean marks by city
print(df.groupby("city")["marks"].mean())

city
Delhi     85.333333
Mumbai    88.500000
Name: marks, dtype: float64

In [42]:
# Multiple Aggregations
import pandas as pd

df = pd.read_json("data1.json")

print(df.groupby("age")["marks"].agg(["mean","median", "max", "min"]))

     mean  median  max  min
age
23   88.5    88.5   92   85
24   82.4    78.0   90   78

In [5]:
# Multiple Aggregations
import pandas as pd

df = pd.read_json("data1.json")

print(df.groupby("city")["marks"].agg(["mean", "max", "min"]))

             mean  max  min
city
Delhi   85.333333   90   78
Mumbai  88.500000   92   85

In [4]:
# Count Values
import pandas as pd

df = pd.read_json("data1.json")

print(df.groupby("city")["name"].count())

# Count students per city.

city
Delhi     3
Mumbai    2
Name: name, dtype: int64

In [43]:
# Group by Multiple Columns
print(df.groupby(["city", "marks"])["name"].count())

# Hierarchical grouping.

city    marks
Delhi   78       3
        88       1
        90       1
Mumbai  85       1
        92       1
Name: name, dtype: int64

In [46]:
# Reset Index
result = df.groupby("city")["marks"].mean().reset_index()
print(result)

# Converts grouped result back to DataFrame.

     city  marks
0   Delhi   82.4
1  Mumbai   88.5

In [48]:
# Sorting Group Results
print(df.groupby("city")["marks"].mean().sort_values(ascending=False))

city
Mumbai    88.5
Delhi     82.4
Name: marks, dtype: float64

In [9]:
# Named Aggregation

df.groupby("city").agg(
    avg_marks=("marks", "mean"),
    max_marks=("marks", "max")
)

        avg_marks  max_marks
city
Delhi   85.333333         90
Mumbai  88.500000         92

In [11]:
# Apply Custom Function
df.groupby("city")["marks"].apply(lambda x: x.max() - x.min())

# Difference between highest and lowest marks.

city
Delhi     12
Mumbai     7
Name: marks, dtype: int64

In [56]:
# Size vs Count
df.groupby("city").size()

city
Delhi     5
Mumbai    2
dtype: int64

In [57]:
df.groupby("city")["name"].count()

city
Delhi     3
Mumbai    2
Name: name, dtype: int64

In [58]:
df.groupby("city").count()

        name  marks  age
city
Delhi      3      5    5
Mumbai     2      2    2

In [ ]:
# Difference
# size → counts all rows
# count → ignores null values