In [ ]:
# Merging & Joining DataFrames in pandas

In [2]:
import pandas as pd

df_students = pd.read_json("student3.json")
df_marks = pd.read_json("marks.json")

print(df_students)
print(df_marks)

   id   name  marks
0   1  Sahil     95
1   2   Riya     90
2   3   Aman     88
3   4   Neha     90
4   5  Nehal     90
   id  marks
0   1     95
1   2     85
2   3     88
3   5     95
4   4     95

In [ ]:
# What is Merge?
# Merge = combining two DataFrames based on a common column (like SQL JOIN)

In [2]:
# Inner Join 

df = pd.merge(df_students, df_marks, on="id", how="inner")

print(df)
# Only matching IDs are included.

   id   name  marks
0   1  Sahil     90
1   2   Riya     85
2   3   Aman     88

In [3]:
# Left Join
df = pd.merge(df_students, df_marks, on="id", how="left")

print(df)
# All students kept, missing marks = NaN

   id   name  marks
0   1  Sahil   90.0
1   2   Riya   85.0
2   3   Aman   88.0
3   4   Neha    NaN

In [4]:
# Right Join
df = pd.merge(df_students, df_marks, on="id", how="right")

print(df)
# All marks kept, even if student missing.

   id   name  marks
0   1  Sahil     90
1   2   Riya     85
2   3   Aman     88
3   5    NaN     95

In [5]:
# Outer Join

df = pd.merge(df_students, df_marks, on="id", how="outer")

print(df)

# All data from both tables.

   id   name  marks
0   1  Sahil   90.0
1   2   Riya   85.0
2   3   Aman   88.0
3   4   Neha    NaN
4   5    NaN   95.0

In [ ]:
# Summary:
# Join Type	  Result
# inner	     common only
# left	     all left
# right	     all right
# outer	     everything

In [3]:
# Merge on Different Column Names
pd.merge(df_students, df_marks, left_on="id", right_on="id")

   id   name  marks
0   1  Sahil     90
1   2   Riya     85
2   3   Aman     88

In [5]:
# Merge on Multiple Columns
import pandas as pd
df1= pd.read_json("student3.json")
df2=pd.read_json("marks.json")

pd.merge(df1, df2, on=["id","marks"])

   id   name  marks
0   1  Sahil     95
1   3   Aman     88

In [6]:
# Suffixes:If same column names exist

pd.merge(df1, df2, on="id", suffixes=("_left", "_right"))

   id   name  marks_left  marks_right
0   1  Sahil          95           95
1   2   Riya          90           85
2   3   Aman          88           88
3   4   Neha          90           95
4   5  Nehal          90           95

In [9]:
# join() Method:Alternative to merge.
# import pandas as pd
# df1= pd.read_json("student3.json")
# df2=pd.read_json("marks.json")

df1.join(df2.set_index("id"), on ="id" ,lsuffix="_left", rsuffix="_right")
# Join works on index.

   id   name  marks_left  marks_right
0   1  Sahil          95           95
1   2   Riya          90           85
2   3   Aman          88           88
3   4   Neha          90           95
4   5  Nehal          90           95

In [8]:
df = pd.merge(df_students, df_marks, on="id", how="left")

missing = df[df["marks"].isnull()]

print("All Data:\n", df)
print("Students without marks:\n", missing)

All Data:
    id   name  marks
0   1  Sahil   90.0
1   2   Riya   85.0
2   3   Aman   88.0
3   4   Neha    NaN
Students without marks:
    id  name  marks
3   4  Neha    NaN