In [ ]:
# Handling Missing Values in Pandas
# Missing values = data not available
# Represented as:
# NaN (Not a Number)
# None

In [1]:
import pandas as pd

df = pd.read_json("student2.json")

print(df)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   NaN   85.0   Mumbai
2   Aman  23.0    NaN     Pune
3   Neha  21.0   92.0     None
4  Karan   NaN   78.0  Chennai

In [3]:
# Detect Missing Values
# isnull()
import pandas as pd

df = pd.read_json("student2.json")

print(df.isnull())

    name    age  marks   city
0  False  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4  False   True  False  False

In [ ]:
# True → missing
# False → present

In [4]:
# Count missing values

import pandas as pd

df = pd.read_json("student2.json")

print(df.isnull().sum())

name     0
age      2
marks    1
city     1
dtype: int64

In [6]:
# notnull():Opposite of isnull.
import pandas as pd

df = pd.read_json("student2.json")

print(df.notnull())

   name    age  marks   city
0  True   True   True   True
1  True  False   True   True
2  True   True  False   True
3  True   True   True  False
4  True  False   True   True

In [8]:
# Drop Missing Values
# dropna():Remove rows with missing values.
import pandas as pd

df = pd.read_json("student2.json")

df1 = df.dropna()

print(df1)

# Removes any row containing at least one null.

    name   age  marks   city
0  Sahil  24.0   90.0  Delhi

In [25]:
# Drop only specific columns
import pandas as pd

df = pd.read_json("student2.json")

df.dropna(subset=["marks","age"])

# Only remove rows where marks is missing.

    name   age  marks   city
0  Sahil  24.0   90.0  Delhi
3   Neha  21.0   92.0   None

In [26]:
# Drop only specific columns
import pandas as pd

df = pd.read_json("student2.json")

vc=df.dropna(subset=["marks","age"])
print(vc)

# Only remove rows where marks is missing.

    name   age  marks   city
0  Sahil  24.0   90.0  Delhi
3   Neha  21.0   92.0   None

In [28]:
# Drop only specific columns
import pandas as pd

df = pd.read_json("student2.json")

df.dropna(subset=["marks"])


# Only remove rows where marks is missing.

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   NaN   85.0   Mumbai
3   Neha  21.0   92.0     None
4  Karan   NaN   78.0  Chennai

In [21]:
# Drop only specific columns
import pandas as pd

df = pd.read_json("student2.json")

df.dropna(subset=["city"])

# Only remove rows where marks is missing.

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   NaN   85.0   Mumbai
2   Aman  23.0    NaN     Pune
4  Karan   NaN   78.0  Chennai

In [11]:
# axis parameter
import pandas as pd

df = pd.read_json("student2.json")

sb = df.dropna(axis=1)

print(sb)
# Removes columns with null values.

    name
0  Sahil
1   Riya
2   Aman
3   Neha
4  Karan

In [10]:
# axis parameter
import pandas as pd

df = pd.read_json("student2.json")

sb = df.dropna(axis=0)

print(sb)
# Removes columns with null values.

    name   age  marks   city
0  Sahil  24.0   90.0  Delhi

In [20]:
# how parameter:Removes rows only if ALL values are null.
import pandas as pd

df = pd.read_json("student2.json")

df.dropna(how="all")

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   NaN   85.0   Mumbai
2   Aman  23.0    NaN     Pune
3   Neha  21.0   92.0     None
4  Karan   NaN   78.0  Chennai

In [18]:
# how parameter:Removes rows only if ALL values are null.
import pandas as pd

df = pd.read_json("student2.json")

vc = df.dropna(how="all")

print(vc)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   NaN   85.0   Mumbai
2   Aman  23.0    NaN     Pune
3   Neha  21.0   92.0     None
4  Karan   NaN   78.0  Chennai

In [37]:
# Fill Missing Values
# fillna():Replace missing values.
import pandas as pd

df = pd.read_json("student2.json")

df["age"].fillna(24)

# print(df)

0    24.0
1    24.0
2    23.0
3    21.0
4    24.0
5    24.0
Name: age, dtype: float64

In [37]:
# Fill Missing Values
# fillna():Replace missing values.
import pandas as pd

df = pd.read_json("student2.json")

df["age"].fillna(24)

# print(df)

0    24.0
1    24.0
2    23.0
3    21.0
4    24.0
5    24.0
Name: age, dtype: float64

In [46]:
import pandas as pd

df = pd.read_json("student2.json")

df[["age", "marks"]] = df[["age", "marks"]].fillna({
    "age": 24.0,
    "marks": 33.0
})
print(df)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya  24.0   85.0   Mumbai
2   Aman  23.0   33.0     Pune
3   Neha  21.0   92.0     None
4  Karan  24.0   78.0  Chennai
5   None  24.0   33.0     None

In [16]:
import pandas as pd

df = pd.read_json("student2.json")

df["marks"].fillna(df["marks"].mean(), inplace=True)

print(df)

# Mean = average of column.

    name   age  marks     city
0  Sahil  24.0  90.00    Delhi
1   Riya   NaN  85.00   Mumbai
2   Aman  23.0  86.25     Pune
3   Neha  21.0  92.00     None
4  Karan   NaN  78.00  Chennai

C:\Users\hp\AppData\Local\Temp\ipykernel_17412\199134617.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(df["marks"].mean(), inplace=True)

In [49]:
import pandas as pd

df = pd.read_json("student2.json")

df["marks"].fillna(df["marks"].median(), inplace=True)

print(df)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   NaN   85.0   Mumbai
2   Aman  23.0   87.5     Pune
3   Neha  21.0   92.0     None
4  Karan   NaN   78.0  Chennai
5   None   NaN   87.5     None

C:\Users\hp\AppData\Local\Temp\ipykernel_26792\4255593430.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(df["marks"].median(), inplace=True)

In [72]:
# Fill with mode:Mode = most frequent value.#takes value in ascending order

import pandas as pd

df = pd.read_json("student2.json")

df["marks"].fillna(df["marks"].mode()[1], inplace=True)

print(df)

     name   age  marks     city
0   Sahil  24.0   75.0    Delhi
1    Riya   NaN   75.0   Mumbai
2    Aman  23.0   90.0     Pune
3    Neha  21.0   92.0     None
4   Karan   NaN   90.0  Chennai
5  Charan   NaN   90.0  Chennai
6   Taran   NaN   92.0  Chennai

C:\Users\hp\AppData\Local\Temp\ipykernel_26792\154095776.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(df["marks"].mode()[1], inplace=True)

In [73]:
# Fill with mode:Mode = most frequent value.#takes value in ascending order

import pandas as pd

df = pd.read_json("student2.json")

df["city"].fillna(df["city"].mode()[0], inplace=True)

print(df)

     name   age  marks     city
0   Sahil  24.0   75.0    Delhi
1    Riya   NaN   75.0   Mumbai
2    Aman  23.0    NaN     Pune
3    Neha  21.0   92.0  Chennai
4   Karan   NaN   90.0  Chennai
5  Charan   NaN   90.0  Chennai
6   Taran   NaN   92.0  Chennai

C:\Users\hp\AppData\Local\Temp\ipykernel_26792\3056490166.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].fillna(df["city"].mode()[0], inplace=True)

In [22]:
# Forward Fill (ffill):Takes previous value.
import pandas as pd

df = pd.read_json("student2.json")

df.fillna(method="ffill", inplace=True)

print(df)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya  24.0   85.0   Mumbai
2   Aman  23.0   85.0     Pune
3   Neha  21.0   92.0     Pune
4  Karan  21.0   78.0  Chennai

C:\Users\hp\AppData\Local\Temp\ipykernel_17412\3867939199.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)

In [24]:
# Backward Fill (bfill):Takes next value.
import pandas as pd

df = pd.read_json("student2.json")

df.fillna(method="bfill", inplace=True)

print(df)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya  23.0   85.0   Mumbai
2   Aman  23.0   92.0     Pune
3   Neha  21.0   92.0  Chennai
4  Karan   NaN   78.0  Chennai

C:\Users\hp\AppData\Local\Temp\ipykernel_17412\3526022857.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill", inplace=True)

In [25]:
# Replace Missing Values in Entire DataFrame
import pandas as pd

df = pd.read_json("student2.json")

df.fillna(0, inplace=True)

print(df)

    name   age  marks     city
0  Sahil  24.0   90.0    Delhi
1   Riya   0.0   85.0   Mumbai
2   Aman  23.0    0.0     Pune
3   Neha  21.0   92.0        0
4  Karan   0.0   78.0  Chennai

In [76]:
#Check Again After Filling
import pandas as pd

df = pd.read_json("student2.json")

print(df.isnull().sum())

print(df)

name     0
age      4
marks    1
city     1
dtype: int64
     name   age  marks     city
0   Sahil  24.0   75.0    Delhi
1    Riya   NaN   75.0   Mumbai
2    Aman  23.0    NaN     Pune
3    Neha  21.0   92.0     None
4   Karan   NaN   90.0  Chennai
5  Charan   NaN   90.0  Chennai
6   Taran   NaN   92.0  Chennai